In [1]:
import numpy as np
from tensorflow import keras

In [2]:
reviews = ["nice food",
           "amazing restaurant",
           "too good",
           "just loved it!",
           "will go again",
           "horrible food",
           "never go there",
           "poor sefvice",
           "poor quality",
           "needs improvement"
           ]

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
keras.preprocessing.text.one_hot("amazing restaurant", 30)

[12, 3]

In [17]:
vocab_size = 50

encoded_reviews = [keras.preprocessing.text.one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[29, 15], [30, 12], [2, 21], [25, 47, 43], [1, 21, 36], [26, 15], [32, 21, 19], [37, 34], [37, 44], [36, 37]]


In [18]:
max_length = 3
padded_reviews = keras.preprocessing.sequence.pad_sequences(encoded_reviews, maxlen=max_length, padding="post")
print(padded_reviews)

[[29 15  0]
 [30 12  0]
 [ 2 21  0]
 [25 47 43]
 [ 1 21 36]
 [26 15  0]
 [32 21 19]
 [37 34  0]
 [37 44  0]
 [36 37  0]]


In [19]:
embedded_vector_size = 5

model = keras.models.Sequential()
model.add(keras.layers.Embedding(vocab_size, embedded_vector_size, input_length=max_length, name="embedding"))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(1, activation = "sigmoid"))

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [20]:
X = padded_reviews
y = sentiment

In [21]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [22]:
model.fit(X, y, epochs=50, verbose=0)

In [23]:
model.evaluate(X, y)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 1.0000 - loss: 0.6316


[0.6315757036209106, 1.0]

In [25]:
weights = model.get_layer("embedding").get_weights()[0]
len(weights)

50

In [26]:
weights[11]

array([ 0.0310506 ,  0.01082901, -0.017386  , -0.00081372,  0.04679484],
      dtype=float32)